### ISSUE TITLE
Final Jupyter Notebook Setup

### ISSUE THREAD

**Issue by chanteriam** [michplunkett/abortion-legislation-analysis#22]
Set up Jupyter notebook for final analysis, including sections for 

### Project description
- introduction
- research questions and hypotheses
- methods

### Set Up
- package/module imports
- data loading
- data cleaning
- data processing

### Analysis
- NER
- clustering
- topic modeling
- similarity analysis

### Reflection/Discussion

**Comment by michplunkett** [comment]
Gonna spend the day on the homeworks, but I'll hopefully have this setup before the EOD tomorrow.
